In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
ir = LogisticRegression()
ir.fit(x_train, y_train)
ir.score(x_test, y_test)

C:\Users\Hakim Rajpoot\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9648148148148148

In [4]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [5]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [20]:
scores_1=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    x_train, x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]
    
    scores_1.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test)
    scores_svm.append(get_score(svc(), x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RamdomForestClassifier(),x_train,x_test,y_train,y_test))get_score

SyntaxError: invalid syntax (<ipython-input-20-72816aec0d6c>, line 10)

In [22]:
scores_1

[]