### pandas on series

In [2]:
import pandas as pd

In [3]:
s = pd.Series([11,28,72,3,5,8])
s

0    11
1    28
2    72
3     3
4     5
5     8
dtype: int64

In [4]:
print(s.index)
print(s.values)

RangeIndex(start=0, stop=6, step=1)
[11 28 72  3  5  8]


In [5]:
import numpy as np

x = np.array([111,28,72,3,5,8])
print(x)
print(s.values)
# both are the same type:
print(type(s.values),type(x))

[111  28  72   3   5   8]
[11 28 72  3  5  8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
fruits = ['apple','orange','cherries','pears']

S = pd.Series([20,33,52,10], index = fruits)
S1 = pd.Series([17,13,31,32], index = fruits)

print(S + S1)

print("sum of s:", sum(S))

apple       37
orange      46
cherries    83
pears       42
dtype: int64
sum of s: 115
